config/routes.rb
Rails.application.routes.draw do
  root '\campaigns', controller: :campaigns, action: :index

  resources :campaigns, only: %i(index show) do
    resources :investments, only: [:create, :new]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  has_one_attached :image
  has_many :investments, class_name: 'Investment', inverse_of: :campaign, dependent: :destroy
  validates :name, :percentage_raised, :target_amount, :country, :investment_multiple, :sector, presence: true

  def update_percentage_raised
    update!(percentage_raised: investments.pluck(:amount).sum / target_amount * 100.0)
  end
end

app/models/investment.rb
class Investment < ApplicationRecord

  belongs_to :campaign, class_name: 'Campaign', inverse_of: :investments

  validates :amount, :campaign, presence: true
  validate :verify_amount_validity, if: :amount
  validate :verify_currency, if: :currency
  validate :assign_currency, unless: :currency, if: :campaign
  validate :validate_email_format, if: :email

  delegate :currency, to: :campaign, prefix: true

  after_create :update_campaign_percentage_raised

  private

  def verify_amount_validity
    return if is_a_multiple?

    errors.add(:amount, "is not a correct multiple of Investment Multiple!")
  end

  def is_a_multiple?
    investment_multiple = campaign&.investment_multiple
    return false unless investment_multiple.present? && amount >= investment_multiple

    multiple = (amount * 1000000000).to_i % (investment_multiple * 1000000000).to_i
    multiple.zero?
   end

  def update_campaign_percentage_raised
    campaign.update_percentage_raised
  end

  def verify_currency
    return if campaign.present? && currency.downcase == campaign_currency&.downcase

    errors.add(:currency, "does not match with Campaign's currency!")
  end

  def assign_currency
    currency = campaign_currency
  end

  def validate_email_format
    return unless email.present?
    return if email.match?(URI::MailTo::EMAIL_REGEXP)

    errors.add(:email, 'is not a valid email')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base; end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  ALLOWED_ATTRS = Campaign.columns.map { |c| [c.name, c.type] }
  ALLOWED_OPS = %w(> < >= <= = != <> ilike iLIKE)

  def index
    @campaigns = Campaign.where(Campaign.sanitize_sql(filter_query), sanitized_value) if params[:field_name].present?
    @campaigns ||= Campaign.order(:id)

    render json: CampaignSerializer.new(@campaigns).serializable_hash

  rescue StandardError => error
    puts error
    render json: { error: error }, status: :unprocessable_entity
  end

  def show
    @campaign = Campaign.find(params[:id])

    render json: CampaignSerializer.new(@campaign).serializable_hash
  rescue ActiveRecord::RecordNotFound => exception
    render json: { error: exception }, status: :not_found
  end

  private

  def filter_query
    "#{allowed_field_names} #{allowed_operations} ?"
  end

  def allowed_field_names
    field_name = params.dig(:field_name)
    return unless field_name

    raise StandardError, 'Invalid Field Name!' unless ALLOWED_ATTRS.map(&:first).include?(field_name)

    field_name
  end

  def allowed_operations
    operation = params.dig(:operation)
    return unless operation

    raise StandardError, "Invalid Operation! Valid OPERATIONS-> #{ALLOWED_OPS.join(' ')}" unless ALLOWED_OPS.include?(operation)
    raise StandardError, 'Operation not possible for field type' if invalid_operation_for_type?(operation)

    operation.eql?('ilike') ? "iLIKE" : operation
  end

  def invalid_operation_for_type?(operation)
    case ALLOWED_ATTRS.to_h[params.dig(:field_name)]
    when :string
      %w(> < >= <=)
    when :integer
      %w(ilike iLIKE)
    when :float
      %w(ilike iLIKE)
    when :datetime
      %w(ilike iLIKE)
    end.include?(operation)
  end

  def sanitized_value
    value = params.dig(:value)&.gsub(/[^[:alnum:]]+/, '_')
    return "%#{value}%" if %w(ilike iLIKE).include?(params.dig(:operation))

    value
  end
end

app/controllers/investments_controller.rb
class InvestmentsController < ApplicationController

  def new
    @campaign = Campaign.find(params[:campaign_id])
    @investment = Investment.new
  end

  # POST /investments
  def create
    @investment = Investment.new(investment_params.merge(campaign_id: params[:campaign_id]))
    @investment.save!

    render json: @investment, status: :created
  rescue StandardError => error
    puts error
    render json: error, status: :unprocessable_entity
  end

  private

    # Only allow a list of trusted parameters through.
    def investment_params
      params.require(:investment).permit(:amount, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/investments_helper.rb
module InvestmentsHelper
end

app/views/campaigns/index.html.erb
# <p id="notice"><%= notice %></p>

# <h1>Campaigns</h1>

# <table>
#   <thead>
#     <tr>
#       <th colspan="3"></th>
#     </tr>
#   </thead>

#   <tbody>
#     <% @campaigns.each do |campaign| %>

#       <tr>
#         <td><%= link_to 'Show', campaign %></td>
#         <td><%= link_to 'Edit', edit_campaign_path(campaign) %></td>
#         <td><%= link_to 'Destroy', campaign, method: :delete, data: { confirm: 'Are you sure?' } %></td>
#       </tr>
#     <% end %>
#   </tbody>
# </table>

# <br>

# <%= link_to 'New Campaign', new_campaign_path %>

app/views/campaigns/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_campaign_path(@campaign) %> |
<%= link_to 'Back', campaigns_path %>

app/views/investments/_form.html.erb
<%= form_with(model: @investment, url: campaign_investments_path, method: :post) do |form| %>
  <% if investment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@investment.errors.count, "error") %> prohibited this investment from being saved:</h2>

      <ul>
        <% @investment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :amount, "Enter amounts in multiple of #{@campaign.investment_multiple} #{@campaign.currency.upcase}" %>
  <%= form.number_field :amount, value: number_to_currency(form.object.amount.to_f, delimiter: '', unit: ''), step: 0.01 %>
  <br>
  <br>
  <%= form.label :email, "Enter your email address" %>
  <%= form.text_field :email, placeholder: 'Email' %>
  <br>
  <br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/investments/new.html.erb
<h1>New Investment for <%= @campaign.name %></h1>

<%= render 'form', investment: @investment %>

<%= link_to 'Back', campaigns_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Seedrs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>